name: Test-SourceCode

on:
  workflow_call:
    inputs:
      RunsOn:
        type: string
        description: The type of runner to use for the job.
        required: true
      Name:
        type: string
        description: The name of the module to process. Scripts default to the repository name if nothing is specified.
        required: false
      Path:
        type: string
        description: The path to the source code of the module.
        required: false
        default: src
      Debug:
        type: boolean
        description: Enable debug output.
        required: false
        default: false
      Verbose:
        type: boolean
        description: Enable verbose output.
        required: false
        default: false
      Version:
        type: string
        description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
        required: false
      Prerelease:
        type: boolean
        description: Whether to use a prerelease version of the 'GitHub' module.
        required: false
        default: false

permissions:
  contents: read # to checkout the repo and create releases on the repo

jobs:
  TestSourceCode:
    name: Test source code (pwsh, ${{ inputs.runs-on }})
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug
        if: ${{ inputs.Debug }}
        uses: PSModule/Debug@v0

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@v1
        with:
          Debug: ${{ inputs.Debug }}
          Prerelease: ${{ inputs.Prerelease }}
          Verbose: ${{ inputs.Verbose }}
          Version: ${{ inputs.Version }}

      - name: Test source code
        id: test
        uses: PSModule/Test-PSModule@v2
        with:
          Name: ${{ inputs.Name }}
          Path: ${{ inputs.Path }}
          TestType: SourceCode
          Debug: ${{ inputs.Debug }}
          Prerelease: ${{ inputs.Prerelease }}
          Verbose: ${{ inputs.Verbose }}
          Version: ${{ inputs.Version }}
