name: '{{ NAME }}'
description: '{{ DESCRIPTION }}'
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  working-directory:
    description: The working directory where Terraform will be executed
    required: false
  subject:
    description: The subject to greet
    required: false
    default: World

runs:
  using: composite
  steps:
    - name: '{{ NAME }}'
      uses: PSModule/GitHub-Script@v1
      env:
        GITHUB_ACTION_INPUT_subject: ${{ inputs.subject }}
      with:
        Script: |
          # '{{ NAME }}'
          ${{ github.action_path }}\scripts\main.ps1
