site_name: ${{ REPO_NAME }}
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Sono
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        primary: black
        accent: green
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        primary: indigo
        accent: green
        icon: material/toggle-switch
        name: Switch to system preference
  icon:
    repo: material/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight

repo_name: ${{ ORG_NAME }}/${{ REPO_NAME }}
repo_url: https://github.com/${{ ORG_NAME }}/${{ REPO_NAME }}

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - toc:
      permalink: true # Adds a link icon to headings
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details # Enables collapsible admonitions

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jedJWCPAhD
      name: ${{ ORG_NAME }} on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/${{ ORG_NAME }}/
      name: ${{ ORG_NAME }} on GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
