name: Aciton-Test-Publish

run-name: "Aciton-Test-Publish - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTestDefault:
    name: Aciton-Test-Publish - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: ./.github/actions/Initialize

      - name: Aciton-Test-Publish
        uses: ./.github/actions/Publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Verbose: true
          Debug: true
          Name: PSModuleTest
          ModulePath: tests/outputTestRepo/outputs/modules
          APIKey: ${{ secrets.APIKEY }}
          WhatIf: true
