name: Action-Test-Test-Src-Default

run-name: "Action-Test-Test-Src-Default - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ActionTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Action-Test-Test-Src-Default - [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: ./.github/actions/Initialize

      - name: Action-Test-Test-outputs
        uses: ./.github/actions/Test
        id: test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModuleTest
          Path: tests/srcTestRepo/src
          TestType: SourceCode

      - name: Status
        shell: pwsh
        env:
          PASSED: ${{ steps.test.outputs.passed }}
        run: |
          Write-Host "Passed: [$env:PASSED]"
          if ($env:PASSED -ne 'true') {
            exit 1
          }
