name: Build-Site

on:
  workflow_call:
    inputs:
      Settings:
        type: string
        description: The complete settings object.
        required: true

permissions:
  contents: read # to checkout the repo

jobs:
  Build-Site:
    name: Build-Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout Process-PSModule
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: _wf
          persist-credentials: false

      - name: Install-PSModule
        uses: ./_wf/.github/actions/Install-PSModule

      - name: Download docs artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: docs
          path: ${{ fromJson(inputs.Settings).WorkingDirectory }}/outputs/docs

      - name: Install Zensical
        uses: ./_wf/.github/actions/Install-Zensical

      - name: Structure site
        uses: ./_wf/.github/actions/Structure-Site
        with:
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
          Name: ${{ fromJson(inputs.Settings).Name }}

      - name: Build documentation site with Zensical
        uses: ./_wf/.github/actions/Build-ZensicalSite
        with:
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}

      - name: Inject shared site scripts
        uses: ./_wf/.github/actions/Inject-SiteScripts
        with:
          SitePath: ${{ fromJson(inputs.Settings).WorkingDirectory }}/_site
          WorkflowPath: _wf

      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          name: github-pages
          path: ${{ fromJson(inputs.Settings).WorkingDirectory }}/_site
          retention-days: 1
