name: Build-Module

on:
  workflow_call:
    secrets:
      GitHubAppClientId:
        description: The client ID of the GitHub App used for repository API calls.
        required: true
      GitHubAppPrivateKey:
        description: The private key of the GitHub App used for repository API calls.
        required: true
    inputs:
      Settings:
        type: string
        description: The settings object as a JSON string.
        required: true
      ArtifactName:
        type: string
        description: Name of the artifact to upload.
        required: false
        default: module

permissions:
  contents: read # to checkout the repository

jobs:
  Build-Module:
    name: Build-Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout Process-PSModule
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: _wf
          persist-credentials: false

      - name: Create GitHub App token
        id: App-Token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: ${{ secrets.GitHubAppClientId }}
          private-key: ${{ secrets.GitHubAppPrivateKey }}
          repositories: ${{ github.event.repository.name }}

      - name: Build module
        uses: ./_wf/.github/actions/Build-PSModule
        env:
          GH_TOKEN: ${{ steps.App-Token.outputs.token }}
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          Version: ${{ fromJson(inputs.Settings).Publish.Module.Resolution.Version != '' && fromJson(inputs.Settings).Publish.Module.Resolution.Version || '999.0.0' }}
          Prerelease: ${{ fromJson(inputs.Settings).Publish.Module.Resolution.Prerelease }}
          ArtifactName: ${{ inputs.ArtifactName }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
