name: Build-Module

on:
  workflow_call:
    inputs:
      Settings:
        type: string
        description: The settings object as a JSON string.
        required: true
      ArtifactName:
        type: string
        description: Name of the artifact to upload.
        required: false
        default: module

permissions:
  contents: read # to checkout the repository

jobs:
  Build-Module:
    name: Build-Module
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout Process-PSModule
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: _wf
          persist-credentials: false

      - name: Build module
        uses: ./_wf/.github/actions/Build-PSModule
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          Version: ${{ fromJson(inputs.Settings).Module.Version != '' && fromJson(inputs.Settings).Module.Version || '999.0.0' }}
          Prerelease: ${{ fromJson(inputs.Settings).Module.Prerelease }}
          ArtifactName: ${{ inputs.ArtifactName }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
