name: Gather-Tests

on:
  workflow_call:
    inputs:
      Workspace:
        type: string
        description: The path to the workspace.
        required: false
        default: ${{ github.workspace }}
      Debug:
        type: boolean
        description: Enable debug output.
        required: false
        default: false
      Verbose:
        type: boolean
        description: Enable verbose output.
        required: false
        default: false
      Version:
        type: string
        description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
        required: false
        default: ''
      Prerelease:
        type: boolean
        description: Whether to use a prerelease version of the 'GitHub' module.
        required: false
        default: false

permissions:
  contents: read # to checkout the repo

jobs:
  Gather-Tests:
    name: Gather-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug
        if: ${{ inputs.Debug }}
        uses: PSModule/Debug@v0

      - name: Gather-Tests
        shell: pwsh
        run: |
          $rootPath = Resolve-Path -Path '${{ inputs.Workspace }}'
          $testsPath = Join-Path -Path $rootPath -ChildPath 'tests'
          if (-not (Test-Path -Path $testsPath)) {
              Write-Host "No tests found"
              exit 0
          }

          $testSuites = @()
          $testSuites += Get-ChildItem -Path $testsPath -Directory
          if (-not $testSuites) {
              $testSuites += @($testsPath)
          }

          Write-Output $testSuites
