name: Linter

run-name: "Linter - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  Lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint code base
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILTER_REGEX_EXCLUDE: '(tests/src(TestRepo|WithManifestTestRepo)/src/classes/public/.*\.ps1|docs/.*)$'
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          USE_FIND_ALGORITHM: true
