name: Lint-SourceCode

on:
  workflow_call:
    inputs:
      Settings:
        type: string
        description: The settings object as a JSON string.
        required: true

permissions:
  contents: read # to checkout the repo and create releases on the repo

jobs:
  Lint-SourceCode:
    name: Lint-SourceCode (${{ matrix.OSName }})
    runs-on: ${{ matrix.RunsOn }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.Settings).TestSuites.SourceCode }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Lint-SourceCode
        uses: PSModule/Invoke-ScriptAnalyzer@6aeb1bc093b89f9b15c2ac3e5f9ef9e0879dc755 # v4.1.3
        with:
          Debug: ${{ fromJson(inputs.Settings).Debug }}
          Prerelease: ${{ fromJson(inputs.Settings).Prerelease }}
          Verbose: ${{ fromJson(inputs.Settings).Verbose }}
          Version: ${{ fromJson(inputs.Settings).Version }}
          Path: src
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
          TestResult_Enabled: true
          TestResult_TestSuiteName: PSModuleLint-SourceCode-${{ runner.os }}
