name: Publish-Module

on:
  workflow_call:
    secrets:
      APIKey:
        description: The API key for the PowerShell Gallery.
        required: true
      GitHubAppClientId:
        description: The client ID of the GitHub App used for repository API calls.
        required: true
      GitHubAppPrivateKey:
        description: The private key of the GitHub App used for repository API calls.
        required: true
    inputs:
      Settings:
        type: string
        description: The complete settings object.
        required: true

permissions: {}

jobs:
  Publish-Module:
    name: Publish-Module
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Create releases and upload release artifacts.
      pull-requests: write # Comment on pull requests.
    env:
      SETTINGS: ${{ inputs.Settings }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout Process-PSModule
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: _wf
          persist-credentials: false

      - name: Create GitHub App token
        id: App-Token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2
        with:
          app-id: ${{ secrets.GitHubAppClientId }}
          private-key: ${{ secrets.GitHubAppPrivateKey }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-pull-requests: write

      - name: Publish module
        if: fromJson(inputs.Settings).Publish.Module.Resolution.ReleaseType != 'None'
        uses: ./_wf/.github/actions/Publish-PSModule
        env:
          GH_TOKEN: ${{ steps.App-Token.outputs.token }}
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          ModulePath: outputs/module
          APIKey: ${{ secrets.APIKey }}
          WhatIf: ${{ github.repository == 'PSModule/Process-PSModule' }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}

      - name: Create GitHub release
        id: create-github-release
        if: always() && !cancelled() && fromJson(inputs.Settings).Publish.Module.Resolution.ReleaseType != 'None'
        uses: ./_wf/.github/actions/Release-PSModule
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          ModulePath: outputs/module
          ArtifactName: module
          WhatIf: ${{ github.repository == 'PSModule/Process-PSModule' }}
          UsePRTitleAsReleaseName: ${{ fromJson(inputs.Settings).Publish.Module.UsePRTitleAsReleaseName }}
          UsePRBodyAsReleaseNotes: ${{ fromJson(inputs.Settings).Publish.Module.UsePRBodyAsReleaseNotes }}
          UsePRTitleAsNotesHeading: ${{ fromJson(inputs.Settings).Publish.Module.UsePRTitleAsNotesHeading }}
          ReleaseTag: ${{ fromJson(inputs.Settings).Publish.Module.Resolution.FullVersion }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}

      - name: Cleanup prereleases
        if: >-
          always() && !cancelled() &&
          fromJson(inputs.Settings).Publish.Module.Resolution.ReleaseType != 'Prerelease' &&
          (fromJson(inputs.Settings).Publish.Module.Resolution.ReleaseType == 'None' ||
          steps.create-github-release.outcome == 'success')
        uses: ./_wf/.github/actions/Cleanup-PSModulePrereleases
        env:
          GH_TOKEN: ${{ steps.App-Token.outputs.token }}
        with:
          WhatIf: ${{ github.repository == 'PSModule/Process-PSModule' }}
          AutoCleanup: ${{ fromJson(inputs.Settings).Publish.Module.AutoCleanup }}
          ReleaseTag: ${{ steps.create-github-release.outputs.ReleaseTag }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
