name: Publish-Module

on:
  workflow_call:
    secrets:
      APIKey:
        description: The API key for the PowerShell Gallery.
        required: true
    inputs:
      Settings:
        type: string
        description: The complete settings object.
        required: true

permissions:
  contents: write # to checkout the repo, create releases, and upload release artifacts
  pull-requests: write # to comment on PRs

jobs:
  Publish-Module:
    name: Publish-Module
    runs-on: ubuntu-latest
    env:
      SETTINGS: ${{ inputs.Settings }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Publish module
        uses: PSModule/Publish-PSModule@03c0f8b53d0367c85a0f121f98af9b40c817b0e3 # v3.0.0
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          ModulePath: outputs/module
          APIKey: ${{ secrets.APIKEY }}
          WhatIf: ${{ github.repository == 'PSModule/Process-PSModule' }}
          AutoCleanup: ${{ fromJson(inputs.Settings).Publish.Module.AutoCleanup }}
          UsePRTitleAsReleaseName: ${{ fromJson(inputs.Settings).Publish.Module.UsePRTitleAsReleaseName }}
          UsePRBodyAsReleaseNotes: ${{ fromJson(inputs.Settings).Publish.Module.UsePRBodyAsReleaseNotes }}
          UsePRTitleAsNotesHeading: ${{ fromJson(inputs.Settings).Publish.Module.UsePRTitleAsNotesHeading }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
