name: Release

run-name: "Release - ${{ github.event_name }} [${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}] by @${{ github.actor }}"

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
      - '!.github/workflows/Release.yml'
      - '!.github/workflows/Linter.yml'
      - '!.github/workflows/Workflow-Test-*'
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - labeled
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
      - '!.github/workflows/Release.yml'
      - '!.github/workflows/Linter.yml'
      - '!.github/workflows/Workflow-Test-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write # Required to create releases
  pull-requests: write # Required to create comments on the PRs

jobs:
  Release:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Release
        uses: PSModule/Release-GHRepository@750abed0ecab02394554b610dc3aa191e75e3248 # v2.0.3
