name: Test-Module

on:
  workflow_call:
    inputs:
      OS:
        type: string
        description: The operating system to use for the build and test jobs.
        required: true
      Shell:
        type: string
        description: The shell to use for the build and test jobs.
        required: true

jobs:
  TestModule:
    name: Test module (${{ inputs.Shell }}@${{ inputs.OS }})
    runs-on: ${{ inputs.OS }}
    outputs:
      passed: ${{ steps.test.outputs.passed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@v1
        with:
          Version: ${{ inputs.Version }}
          Prerelease: ${{ inputs.Prerelease }}
          Shell: ${{ inputs.Shell }}

      - name: Download module artifact
        uses: actions/download-artifact@v4
        with:
          name: module
          path: ${{ inputs.ModulesOutputPath }}

      - name: Test built module
        id: test
        uses: PSModule/Test-PSModule@v1
        if: ${{ inputs.SkipTests != true }}
        continue-on-error: true
        with:
          Name: ${{ inputs.Name }}
          Path: ${{ inputs.ModulesOutputPath }}
          Shell: ${{ inputs.Shell }}
          TestType: Module
