name: Test-Module

on:
  workflow_call:
    inputs:
      Settings:
        type: string
        description: The settings object as a JSON string.
        required: true

permissions:
  contents: read # to checkout the repo and create releases on the repo

jobs:
  Test-Module:
    name: Test-Module (${{ matrix.OSName }})
    runs-on: ${{ matrix.RunsOn }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.Settings).Test.PSModule.Suites }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Checkout Process-PSModule
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ job.workflow_repository }}
          ref: ${{ job.workflow_sha }}
          path: _wf
          persist-credentials: false

      - name: Download module artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: module
          path: ${{ fromJson(inputs.Settings).WorkingDirectory }}/outputs/module

      - name: Test-Module
        uses: ./_wf/.github/actions/Test-PSModule
        with:
          Name: ${{ fromJson(inputs.Settings).Name }}
          Debug: ${{ fromJson(inputs.Settings).Debug }}
          Prerelease: ${{ fromJson(inputs.Settings).Prerelease }}
          Verbose: ${{ fromJson(inputs.Settings).Verbose }}
          Version: ${{ fromJson(inputs.Settings).Version }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
          Settings: Module

  Lint-Module:
    name: Lint-Module (${{ matrix.OSName }})
    runs-on: ${{ matrix.RunsOn }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.Settings).Test.PSModule.Suites }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Download module artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: module
          path: ${{ fromJson(inputs.Settings).WorkingDirectory }}/outputs/module

      - name: Lint-Module
        uses: PSModule/Invoke-ScriptAnalyzer@4d633e4df1f1fa575949a328839d33c3a0838765 # v5.0.0
        with:
          Path: outputs/module
          Debug: ${{ fromJson(inputs.Settings).Debug }}
          GitHubPrerelease: ${{ fromJson(inputs.Settings).Prerelease }}
          GitHubVersion: ${{ fromJson(inputs.Settings).Version }}
          Verbose: ${{ fromJson(inputs.Settings).Verbose }}
          WorkingDirectory: ${{ fromJson(inputs.Settings).WorkingDirectory }}
          TestResult_Enabled: true
          TestResult_TestSuiteName: PSModuleLint-Module-${{ runner.os }}
