  TestModule:
    name: Test module
    needs: BuildModule
    strategy:
      fail-fast: false
      matrix:
        shell: [pwsh]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - shell: powershell
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@v1
        with:
          Version: ${{ inputs.Version }}
          Prerelease: ${{ inputs.Prerelease }}
          Shell: ${{ matrix.shell }}

      - name: Download module artifact
        uses: actions/download-artifact@v4
        with:
          name: module
          path: ${{ inputs.ModulesOutputPath }}

      - name: Test built module
        uses: PSModule/Test-PSModule@v1
        if: ${{ inputs.SkipTests != true }}
        with:
          Name: ${{ inputs.Name }}
          Path: ${{ inputs.ModulesOutputPath }}
          Shell: ${{ matrix.shell }}
          TestType: 'Module'
