name: Workflow-Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  WorkflowTestDefault:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      Name: 'PSModuleTestWF'
