name: Workflow-Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  WorkflowTestDefault:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      Name: PSModule.Process
      TestProcess: true
