name: Workflow-Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/workflow.yml
      - .github/workflows/Workflow-Test.yml
  pull_request_target:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/Action-Test.yml
      - scripts/**

jobs:
  WorkflowTestDefault:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
