name: Workflow-Test [WithManifest]

run-name: 'Workflow-Test [WithManifest] - ${{ github.event_name }} [${{ github.event.pull_request.title || github.event.head_commit.message || github.ref_name }}] by @${{ github.actor }}'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
      - '!.github/workflows/Release.yml'
      - '!.github/workflows/Linter.yml'
  pull_request:
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
      - '!.github/workflows/Release.yml'
      - '!.github/workflows/Linter.yml'
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

jobs:
  WorkflowTestWithManifest:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/workflow.yml
    secrets:
      APIKey: ${{ secrets.APIKey }}
      TestData: >-
        {
          "secrets": {
            "PSMODULE_TEST_SINGLELINE_SECRET": "${{ secrets.PSMODULE_TEST_SINGLELINE_SECRET }}"
          },
          "variables": {
            "PSMODULE_TEST_VARIABLE": ${{ toJSON(vars.PSMODULE_TEST_VARIABLE) }}
          }
        }
    with:
      WorkingDirectory: tests/srcWithManifestTestRepo
      ImportantFilePatterns: |
        ^src/
        ^README\.md$
        ^\.github/actions/
        ^\.github/workflows/(?!Release\.yml$|Linter\.yml$)
