name: Workflow-Test CI [WithManifest]

run-name: "Workflow-Test CI [WithManifest] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  WorkflowTestCIWithManifest:
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    with:
      Name: PSModuleTest
      Path: tests/srcWithManifest
      ModulesOutputPath: tests/outputs/modules
      DocsOutputPath: tests/outputs/docs
      SkipTests: Linux
