name: Workflow-Test [Default]

run-name: "Workflow-Test [Default] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

jobs:
  WorkflowTestDefault:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      WorkingDirectory: tests/srcTestRepo
      Name: PSModuleTest2
      Debug: true
