name: Workflow-Test CI [WithManifest]

run-name: "Workflow-Test CI [WithManifest] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  WorkflowTestCIWithManifest:
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    with:
      WorkingDirectory: tests/srcWithManifestTestRepo
      Name: PSModuleTest2
