name: Workflow-Test [Default]

run-name: "Workflow-Test [Default] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write
  pages: write
  id-token: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  WorkflowTestDefault:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      Name: PSModuleTest
      Path: tests/src
      ModulesOutputPath: tests/outputs/modules
      DocsOutputPath: tests/outputs/docs
      TestProcess: true
      SkipTests: Module
