name: Verify Workflow

on:
  workflow_call:
  push:
    paths:
      - workflow.yml
      - .github/workflows/Workflow-Test.yml

jobs:
  DefaultTest:
    name: Test Workflow - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Test local workflow
        uses: workflow.yml
