name: Workflow-Test CI [Default]

run-name: "Workflow-Test CI [Default] - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  WorkflowTestCIDefault:
    uses: ./.github/workflows/CI.yml
    secrets: inherit
    with:
      Name: PSModuleTest
      Path: tests/src
      ModulesOutputPath: tests/outputs/modules
      DocsOutputPath: tests/outputs/docs
      SkipTests: Module
